name: Trivy Secret Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  secret-scan:
    name: Run Trivy Secret Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scanners: secret
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          exit-code: '1'
          hide-progress: true
          format: table
          path: "."
