name: Trivy Secret Scan on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target (main) branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Fetch PR branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}:pr-branch

      - name: Get list of changed files
        id: diff
        run: |
          git diff --name-only main pr-branch > changed_files.txt
          cat changed_files.txt

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scanners: secret
          exit-code: '1'
          hide-progress: true
          severity: CRITICAL,HIGH
          format: table
          path: $(cat changed_files.txt | tr '\n' ' ')
